name: Publish Layer Three

on: 
  push:
    branches:
      - releases/layer3

jobs:
  compress_zip:
    uses: ./.github/workflows/compress.yml
    with:
      layer_path: "Layer3"
      layer_name: "layer-three"
  layer3-deploy:
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      id-token: write
    needs: compress_zip
    steps: 
      - name: Source Code Checkout 
        uses: actions/checkout@v4
      - name: Download Artifact and View
        uses: ./.github/actions/download-artifact-and-view
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region: ap-northeast-1
      - name: Upload Layer to AWS Lambda
        uses: ./.github/actions/publish-lambda-layer
        with: 
          layer_name: "layer-three"