name: Publish Layer Two

on: 
  push:
    branches:
      - releases/layer2

env:
  LAYER_PATH: "Layer2"
  LAYER_NAME: "layer-two"

jobs:
  compress_zip:
    uses: ./.github/workflows/compress.yml
    wtih:
      layer_path: $LAYER_PATH
      layer_name: $LAYER_NAME
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      id-token: write
    needs: compress_zip
    steps: 
      - name: Download Artifact and View
        uses: ./.github/actions/download-artifact-and-view
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Upload Layer to AWS Lambda
        uses: ./.github/actions/publish-lambda-layer
        with: 
          layer_name: $LAYER_NAME