name: Deploy Manual
on: 
  push:
    branches:
     - 'releases/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run'
        type: environment
        required: true
      layer_path:
        description: "Enter Layer Path"
        type: choice
        required: true
        options:
          - Layer1
          - Layer2
          - Layer3
      layer_name:
        description: "Enter Layer Name"
        type: choice
        required: true
        options:
          - 'layer-one'
          - 'layer-two'
          - 'layer-three'

jobs:
  compress_zip:
    uses: ./.github/workflows/compress.yml
    with:
      layer_path: ${{ inputs.layer_path }}
      layer_name: ${{ inputs.layer_name }}
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    needs: compress_zip
    steps: 
      - name: Source Code Checkout 
        uses: actions/checkout@v4
      - name: Download Artifact and View
        uses: ./.github/actions/download-artifact-and-view
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region: ap-northeast-1
      - name: Upload Layer to AWS Lambda
        uses: ./.github/actions/publish-lambda-layer
        with: 
          layer_name: ${{ inputs.layer_name }}